#!/bin/bash
# Get the dir of this project
DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)/..
if [[ $# != 1 ]]; then echo "usage: run className"; exit 1; fi
java -cp "$DIR/target/scala-2.13/bril-processing-assembly-0.1.0.jar" "$1"